import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { UserProvider } from '@auth0/nextjs-auth0/client'
import "../assets/styles/main.scss"
import AppHeader from "./(cmps)/app-header"
import { getUser } from "@/services/server/auth/session.service"

// TODO: COTEXTPROVIDER IN ORDER TO USE ON CLIENT COMPONENT ABOUT AUTH

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Ness car pool",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  const user = await getUser()

  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <AppHeader user={user} />
          <main>
            {children}
          </main>
        </body>
      </UserProvider>
    </html>
  )
}