import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { UserProvider } from '@auth0/nextjs-auth0/client'
import "../assets/styles/main.scss"
import AppHeader from "./(cmps)/app-header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Ness car pool",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <AppHeader />
          <main>
            {children}
          </main>
        </body>
      </UserProvider>
    </html>
  )
}